/*
 * Copyright (c) Forge Development LLC
 * SPDX-License-Identifier: LGPL-2.1-only
 */
package net.minecraftforge.renamer.gradle;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

import javax.inject.Inject;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.gradle.api.file.RegularFile;
import org.gradle.api.provider.Provider;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.compile.JavaCompile;
import org.gradle.process.CommandLineArgumentProvider;

abstract class MixinSourceSetConfigImpl implements MixinSourceSetConfig {
	private static final Logger LOGGER = LogManager.getLogger(MixinConfig.class);
	private final RenamerExtensionImpl ext;
	final SourceSet sourceSet;

	@Inject
	public MixinSourceSetConfigImpl(RenamerExtensionImpl ext, MixinConfigImpl main, String name, SourceSet sourceSet) {
		this.ext = ext;
		this.sourceSet = sourceSet;

		this.getRefMap().convention(name + ".refmap.json");
		this.getDisableTargetValidator().convention(main.getDisableTargetValidator());
		this.getDisableTargetExport().convention(main.getDisableTargetExport());
		this.getDisableOverwriteChecker().convention(main.getDisableOverwriteChecker());
		this.getOverwriteErrorLevel().convention(main.getOverwriteErrorLevel());
		this.getDefaultObfuscationEnv().convention(main.getDefaultObfuscationEnv());
		this.getMappingTypes().convention(main.getMappingTypes());
		this.getTokens().convention(main.getTokens());
		this.getExtraMappings().convention(main.getExtraMappings());
		this.getQuiet().convention(main.getQuiet());
		this.getShowMessageTypes().convention(main.getShowMessageTypes());
		this.getMessages().convention(main.getMessages());

		this.ext.defaultMixinBehavior = false;
		var project = this.ext.getProject();
		var sourceExt = sourceSet.getExtensions().getExtraProperties();
		var compile = project.getTasks().named(sourceSet.getCompileJavaTaskName(), JavaCompile.class);
		var refMapFile = compile.map(task -> new File(task.getTemporaryDir(), task.getName() + "-refmap.json"));
		var mappingFile = compile.map(task -> new File(task.getTemporaryDir(), task.getName() + "-mappings.tsrg"));
		sourceExt.set("refMapFile", refMapFile);

		compile.configure(task -> {
			var mappings = main.getMappings().flatMap(ConvertMappings::getOutput);
			task.getInputs().files(mappings);
			// These are generated by the AP
			var extra = task.getExtensions().getExtraProperties();
			extra.set("refMapFile", refMapFile);
			extra.set("outTsrgFile", mappingFile);
			extra.set("refMap", MixinSourceSetConfigImpl.this.getRefMap());
			task.getOptions().getCompilerArgumentProviders().add(
				project.getObjects().newInstance(CompilerArgs.class, MixinSourceSetConfigImpl.this, task, mappings)
			);
		});

		// Add our output mappings to the merge task
		main.getGeneratedMappings().configure(task -> task.map(mappingFile));
	}

	abstract static class CompilerArgs implements CommandLineArgumentProvider {
		private final MixinSourceSetConfigImpl config;
		private final JavaCompile compile;
		private final Provider<RegularFile> mappings;

		@Inject
		public CompilerArgs(MixinSourceSetConfigImpl config, JavaCompile compile, Provider<RegularFile> mappings) {
			this.config = config;
			this.compile = compile;
			this.mappings = mappings;
		}

		@Override
		public Iterable<String> asArguments() {
			var ext = this.compile.getExtensions().getExtraProperties();

			var ret = new ArrayList<String>();
			ret.add("-AreobfTsrgFile=" + mappings.get().getAsFile().getAbsolutePath());
			ret.add("-AoutTsrgFile=" + file(ext.get("outTsrgFile")).getAbsolutePath());
			ret.add("-AoutRefMapFile=" + file(ext.get("refMapFile")).getAbsolutePath());
			if (config.getDisableTargetValidator().getOrElse(false))
				ret.add("-AdisableTargetValidator=true");
			if (config.getDisableTargetExport().getOrElse(false))
				ret.add("-AdisableTargetExport=true");
			if (config.getDisableOverwriteChecker().getOrElse(false))
				ret.add("-AdisableOverwriteChecker=true");
			if (config.getQuiet().getOrElse(false))
				ret.add("-Aquiet=true");
			if (config.getShowMessageTypes().getOrElse(false))
				ret.add("-DshowMessageTypes=true");
			if (config.getOverwriteErrorLevel().isPresent())
				ret.add("-AoverwriteErrorLevel=" + config.getOverwriteErrorLevel().get().trim());
			if (config.getDefaultObfuscationEnv().isPresent())
				ret.add("-AdefaultObfuscationEnv=" + config.getDefaultObfuscationEnv().getOrElse("searge"));
			var mappingTypes = config.getMappingTypes().getOrElse(List.of());
			if (!mappingTypes.isEmpty())
				ret.add("-AmappingTypes=" + String.join(",", mappingTypes));
			var tokens = config.getTokens().getOrElse(Map.of());
			if (!tokens.isEmpty()) {
				var buf = new StringBuilder();
				buf.append("-Atokens=");
				for (var entry : tokens.entrySet()) {
					if (entry.getKey().indexOf(';') != -1 || entry.getValue().indexOf(';') != -1)
						throw new IllegalArgumentException("Invalid token: " + entry.getKey() + '=' + entry.getValue());
					buf.append(entry.getKey()).append('=').append(entry.getValue()).append(';');
				}
				ret.add(buf.toString());
			}
			var extraMappings = config.getExtraMappings().getFiles();
			if (!extraMappings.isEmpty()) {
				var buf = new StringBuilder();
				buf.append("-AreobfTsrgFiles=");
				for (var file : extraMappings)
					buf.append(file.getAbsolutePath()).append(';');
				ret.add(buf.toString());
			}
			var messages = config.getMessages().getOrElse(Map.of());
			if (!messages.isEmpty()) {
				var keyPattern = Pattern.compile("^[A-Z]+[A-Z]_+$");
				var valuePattern = Pattern.compile("^(note|warning|error|disabled)$");
				for (var entry : messages.entrySet()) {
					if (!keyPattern.matcher(entry.getKey()).matches() || !valuePattern.matcher(entry.getValue()).matches())
						throw new IllegalArgumentException("Invalid message config: " + entry.getKey() + '=' + entry.getValue());
					ret.add("-AMSG_" + entry.getKey() + '=' + entry.getValue());
				}
			}

			LOGGER.info("[Renamer][Mixin] Compile Args: " + ret);

			return ret;
		}

		private static final File file(Object value) {
			if (value instanceof File file)
				return file;
			if (value instanceof Provider<?> provider)
				return file(provider.get());
			throw new IllegalArgumentException("Unsupported file argument: " + value);
		}
	}
}
