/*
 * Copyright (c) Forge Development LLC
 * SPDX-License-Identifier: LGPL-2.1-only
 */
package net.minecraftforge.renamer.gradle;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

import javax.inject.Inject;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.codehaus.groovy.runtime.InvokerHelper;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.RegularFile;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.MapProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.Provider;
import org.gradle.api.tasks.SourceSet;
import org.gradle.api.tasks.compile.JavaCompile;
import org.gradle.process.CommandLineArgumentProvider;

abstract class MixinConfigImpl implements MixinConfig {
	private static final Logger LOGGER = LogManager.getLogger(MixinConfig.class);
	private final RenamerExtensionImpl ext;

	public abstract Property<String> getConfig();
	public abstract Property<String> getRefMap();
	public abstract Property<Boolean> getDisableTargetValidator();
	public abstract Property<Boolean> getDisableTargetExport();
	public abstract Property<Boolean> getDisableOverwriteChecker();
	public abstract Property<String> getOverwriteErrorLevel();
	public abstract Property<String> getDefaultObfuscationEnv();
	public abstract ListProperty<String> getMappingTypes();
	public abstract MapProperty<String, String> getTokens();
	public abstract ConfigurableFileCollection getExtraMappings();
	public abstract Property<Boolean> getQuiet();
	public abstract Property<Boolean> getShowMessageTypes();
	public abstract MapProperty<String, String> getMessages();

	@Inject
	public MixinConfigImpl(RenamerExtensionImpl ext) {
		this.ext = ext;
		this.getMappingTypes().convention(List.of("tsrg"));

		/*
		 * Mixin Magic:
		 *   Run Configs:
		 *     Args:
		 *       --mixin.config <filename> - the Mixin config file, I think users should manually specify this
		 *
		 *     System Property:
		 *       mixin.env.disableRefMap = true - Disable ref maps. Would be the preferred option once Renamer supports renaming mixins
		 *       mixin.env.remapRefMap = true/false - True if we need to remap refmaps,
		 *       mixin.env.refMapRemappingFile = <map file> - The map needs to be Dependency runtime -> Dev Runtime So typically SRG->Named
		 *
		 *  Compile:
		 *    -AreobfTsrgFile=
		 *    -AoutTsrgFile=
		 *    -AoutRefMapfile=
		 *    -AdisableTargetValidator=true
		 *    -AdisableTargetExport=true
		 *    -AdisableOverwriteChecker=true
		 *    -Aquiet=true
		 *    -DshowMessageTypes=true
		 *    -AoverwriteErrorLevel=level
		 *    -AdefaultObfuscationEnv=searge
		 *    -AmappingTypes=tsrg
		 *    -Atokens=key=value;
		 *    -AreobfTsrgFiles=ExtraMapping.tsrg;
		 *    -AMSG_{NAME}={value}
		 *    Not Supported:
		 *      -ApluginVersion=MixinGradlePlugin.VERSION
		 *      -AdependencyTargetsFile
		 */
	}

	public void sourceset(SourceSet sourceSet) {
		ext.defaultMixinBehavior = false;
		var project = ext.getProject();
		var sourceExt = sourceSet.getExtensions().getExtraProperties();
		var compile = project.getTasks().named(sourceSet.getCompileJavaTaskName(), JavaCompile.class);
		var refMapFile = compile.map(task -> new File(task.getTemporaryDir(), task.getName() + "-refmap.json"));
		var mappingFile = compile.map(task -> new File(task.getTemporaryDir(), task.getName() + "-mappings.tsrg"));
		sourceExt.set("refMapFile", refMapFile);

		compile.configure(task -> {
			var mappings = ext.mixinMappings.flatMap(ConvertMappings::getOutput);
			task.getInputs().files(mappings);
			// These are generated by the AP
			var extra = task.getExtensions().getExtraProperties();
			extra.set("refMapFile", refMapFile);
			extra.set("outTsrgFile", mappingFile);
			extra.set("refMap", MixinConfigImpl.this.getRefMap());
			task.getOptions().getCompilerArgumentProviders().add(
				project.getObjects().newInstance(CompilerArgs.class, MixinConfigImpl.this, task, mappings)
			);
		});
	}

	public void run(Object runConfig) {
		LOGGER.info("[Renamer][Mixin] Configuring Run: " + InvokerHelper.getProperty(runConfig, "name"));
		InvokerHelper.invokeMethod(runConfig, "args", this.getConfig().map(cfg -> List.of("--mixin.config", cfg)));
		//InvokerHelper.invokeMethod(runConfig, "systemProperty", new String[]{"mixin.env.disableRefMap", "true"});
		InvokerHelper.invokeMethod(runConfig, "systemProperties", this.ext.mixinMappings.flatMap(task -> task.getOutput()).map(
			file -> Map.of(
				"mixin.env.remapRefMap", "true",
				"mixin.env.refMapRemappingFile", file.getAsFile().getAbsolutePath()
			)
		));
	}

	abstract static class CompilerArgs implements CommandLineArgumentProvider {
		private final MixinConfigImpl config;
		private final JavaCompile compile;
		private final Provider<RegularFile> mappings;

		@Inject
		public CompilerArgs(MixinConfigImpl config, JavaCompile compile, Provider<RegularFile> mappings) {
			this.config = config;
			this.compile = compile;
			this.mappings = mappings;
		}

		@Override
		public Iterable<String> asArguments() {
			var ext = this.compile.getExtensions().getExtraProperties();

			var ret = new ArrayList<String>();
			ret.add("-AreobfTsrgFile=" + mappings.get().getAsFile().getAbsolutePath());
			ret.add("-AoutTsrgFile=" + file(ext.get("outTsrgFile")).getAbsolutePath());
			ret.add("-AoutRefMapFile=" + file(ext.get("refMapFile")).getAbsolutePath());
			if (config.getDisableTargetExport().getOrElse(false))
				ret.add("-AdisableTargetValidator=true");
			if (config.getDisableTargetExport().getOrElse(false))
				ret.add("-AdisableTargetExport=true");
			if (config.getDisableOverwriteChecker().getOrElse(false))
				ret.add("-AdisableOverwriteChecker=true");
			if (config.getQuiet().getOrElse(false))
				ret.add("-Aquiet=true");
			if (config.getShowMessageTypes().getOrElse(false))
				ret.add("-DshowMessageTypes=true");
			if (config.getOverwriteErrorLevel().isPresent())
				ret.add("-AoverwriteErrorLevel=" + config.getOverwriteErrorLevel().get().trim());
			if (config.getDefaultObfuscationEnv().isPresent())
				ret.add("-AdefaultObfuscationEnv=" + config.getDefaultObfuscationEnv().get());
			var mappingTypes = config.getMappingTypes().getOrElse(List.of());
			if (!mappingTypes.isEmpty())
				ret.add("-AmappingTypes=" + String.join(",", mappingTypes));
			var tokens = config.getTokens().getOrElse(Map.of());
			if (!tokens.isEmpty()) {
				var buf = new StringBuilder();
				buf.append("-Atokens=");
				for (var entry : tokens.entrySet()) {
					if (entry.getKey().indexOf(';') != -1 || entry.getValue().indexOf(';') != -1)
						throw new IllegalArgumentException("Invalid token: " + entry.getKey() + '=' + entry.getValue());
					buf.append(entry.getKey()).append('=').append(entry.getValue()).append(';');
				}
				ret.add(buf.toString());
			}
			var extraMappings = config.getExtraMappings().getFiles();
			if (!extraMappings.isEmpty()) {
				var buf = new StringBuilder();
				buf.append("-AreobfTsrgFiles=");
				for (var file : extraMappings)
					buf.append(file.getAbsolutePath()).append(';');
				ret.add(buf.toString());
			}
			var messages = config.getMessages().getOrElse(Map.of());
			if (!messages.isEmpty()) {
				var keyPattern = Pattern.compile("^[A-Z]+[A-Z]_+$");
				var valuePattern = Pattern.compile("^(note|warning|error|disabled)$");
				for (var entry : messages.entrySet()) {
					if (!keyPattern.matcher(entry.getKey()).matches() || !valuePattern.matcher(entry.getValue()).matches())
						throw new IllegalArgumentException("Invalid message config: " + entry.getKey() + '=' + entry.getValue());
					ret.add("-AMSG_" + entry.getKey() + '=' + entry.getValue());
				}
			}

			LOGGER.warn("[Renamer][Mixin] Compile Args: " + ret);

			return ret;
		}

		private static final File file(Object value) {
			if (value instanceof File file)
				return file;
			if (value instanceof Provider<?> provider)
				return file(provider.get());
			throw new IllegalArgumentException("Unsupported file argument: " + value);
		}
	}
}
